---
- name: "Starting Redis container (tests)"
  docker_container:
    name: pizza-express-backend
    image: redis:latest
    detach: yes
    ports:
      - '127.0.0.1:6379:6379'
  notify:
    Cleanup containers


- name: "Run NPM install (tests)"
  command: "npm install --scripts-prepend-node-path"
  args:
    chdir: "{{app_dir}}"
  register: _npm_install

- debug:
    msg: "{{_npm_install}}"
  

- name: "Run Application tests (tests)"
  command: "npm test --scripts-prepend-node-path"
  args:
    chdir: "{{app_dir}}"
  register: _npm_install

- debug:
    msg: "{{_npm_install}}"

    
- name: "Build Application container: {{app_image}}:{{app_tag}} (build)"
  docker_image:
    build:
      path: "{{app_dir}}"
      pull: no
    name: "{{app_image}}"
    tag: "{{app_tag}}"  
    source: build

  
- name: "Starting Application container (tests): {{app_image}}:{{app_tag}} (tests)"
  docker_container:
    name: pizza-express-fronted
    image: "{{app_image}}:{{app_tag}}"
    detach: yes
    network_mode: host


- name: "Verify service code 200 (tests)"
  uri:
    url: "http://localhost:8081"


- name: "Push Application with latest tag: {{app_image}}:latest (build)"
  docker_image:
    name: "{{app_image}}:{{app_tag}}"
    repository: "{{app_image}}:latest"
    push: yes
    source: local
...
