---
- name: "Starting Redis container (tests)"
  docker_container:
    name: pizza-express-backend
    image: redis:latest
    detach: yes
    ports:
      - '127.0.0.1:6379:6379'
  notify:
    Cleanup containers


# Using node container during a runtime, to make sure our Env remains clean as possible
- name: "Run NPM install (tests)"
  command: "docker run --interactive --rm --volume {{app_dir}}:/pwd --workdir /pwd node:8.4.0-alpine npm install"
  register: _npm_install

- debug:
    msg: "{{_npm_install}}"
  

# Using network host in order to test the application with the Redis available on the localhost:6379
- name: "Run Application tests (tests)"
  command: "docker run --interactive --network host --rm --volume {{app_dir}}:/pwd --workdir /pwd node:8.4.0-alpine npm test"
  register: _npm_install

- debug:
    msg: "{{_npm_install}}"

    
- name: "Build Application container: {{app_image}}:{{app_tag}} (build)"
  docker_image:
    build:
      path: "{{app_dir}}"
      pull: no
    name: "{{app_image}}"
    tag: "{{app_tag}}"  
    source: build

  
- name: "Starting Application container (tests): {{app_image}}:{{app_tag}} (tests)"
  docker_container:
    name: pizza-express-fronted
    image: "{{app_image}}:{{app_tag}}"
    detach: yes
    network_mode: host


- name: "Verify service code 200 (tests)"
  uri:
    url: "http://localhost:8081"


- name: "Push Application with latest tag: {{app_image}}:latest (build)"
  docker_image:
    name: "{{app_image}}:{{app_tag}}"
    tag: latest
    push: yes
    source: local
...
