---
# handlers file for builder
- name: Cleanup docker compose
  docker_compose:
    project_name: pizza-express
    state: absent
    project_src: "{{app_dir}}"

- name: "Cleanup containers"
  docker_container:
    name: "{{item}}"
    state: absent
  with_items:
    - pizza-express-fronted
    - pizza-express-backend

